name: crcrme_stage_form_demo
description: A new Flutter project.
version: 1.0.0+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    nanoid: ^1.0.0
    autocomplete_textfield: ^2.0.1
    collection: ^1.16.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/jobs-data.json
